"""App Generator - scaffolds the full project structure."""

import json
import os
import shutil
from pathlib import Path
from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn

from pyreactor_forge.generators.backend.fastapi import FastAPIGenerator
from pyreactor_forge.generators.backend.django import DjangoGenerator
from pyreactor_forge.generators.backend.flask import FlaskGenerator
from pyreactor_forge.generators.frontend import FrontendGenerator
from pyreactor_forge.generators.devops import DevOpsGenerator

console = Console()


class AppGenerator:
    def __init__(self, config: dict):
        self.config = config
        self.name = config["name"]
        self.slug = self.name.lower().replace(" ", "-").replace("_", "-")
        self.output_dir = Path(config.get("output_dir", ".")) / self.slug

    def generate(self):
        if self.output_dir.exists():
            raise FileExistsError(
                f"Directory '{self.output_dir}' already exists. "
                "Please remove it or choose a different name."
            )

        self.output_dir.mkdir(parents=True)

        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console,
        ) as progress:
            # Backend
            task = progress.add_task("[cyan]Generating backend...", total=None)
            self._generate_backend()
            progress.update(task, description="[green]✓ Backend generated")

            # Frontend
            task2 = progress.add_task("[cyan]Generating frontend...", total=None)
            self._generate_frontend()
            progress.update(task2, description="[green]✓ Frontend generated")

            # DevOps
            if self.config.get("docker") or self.config.get("ci") != "none":
                task3 = progress.add_task("[cyan]Generating DevOps config...", total=None)
                self._generate_devops()
                progress.update(task3, description="[green]✓ DevOps config generated")

            # Root files
            task4 = progress.add_task("[cyan]Writing project files...", total=None)
            self._write_root_files()
            progress.update(task4, description="[green]✓ Project files written")

    def _generate_backend(self):
        backend = self.config["backend"]
        backend_dir = self.output_dir / "backend"
        backend_dir.mkdir()

        if backend == "fastapi":
            gen = FastAPIGenerator(self.config, backend_dir)
        elif backend == "django":
            gen = DjangoGenerator(self.config, backend_dir)
        else:
            gen = FlaskGenerator(self.config, backend_dir)

        gen.generate()

    def _generate_frontend(self):
        frontend_dir = self.output_dir / "frontend"
        frontend_dir.mkdir()
        gen = FrontendGenerator(self.config, frontend_dir)
        gen.generate()

    def _generate_devops(self):
        gen = DevOpsGenerator(self.config, self.output_dir)
        gen.generate()

    def _write_root_files(self):
        # .pyforge.json - project metadata
        meta = {
            "name": self.name,
            "slug": self.slug,
            "backend": self.config["backend"],
            "frontend": self.config["frontend"],
            "database": self.config["database"],
            "auth": self.config["auth"],
            "version": "0.1.0",
        }
        with open(self.output_dir / ".pyforge.json", "w", encoding="utf-8") as f:
            json.dump(meta, f, indent=2)

        # Root README
        readme = self._render_readme()
        (self.output_dir / "README.md").write_text(readme, encoding="utf-8")

        # Root .gitignore
        (self.output_dir / ".gitignore").write_text(ROOT_GITIGNORE, encoding="utf-8")

        # Makefile
        (self.output_dir / "Makefile").write_text(self._render_makefile(), encoding="utf-8")

    def _render_readme(self):
        name = self.name
        backend = self.config["backend"]
        frontend = self.config["frontend"]
        db = self.config["database"]
        auth = self.config["auth"]

        return f"""# {name}

> Generated by [PyReactor Forge](https://github.com/panosadamop/pyreactor-forge) — Full-stack Python + React generator.

## Stack

| Layer      | Technology                          |
|------------|-------------------------------------|
| Backend    | {backend.capitalize()}              |
| Frontend   | {frontend.upper()}                  |
| Database   | {db.capitalize()}                   |
| Auth       | {auth.upper()}                      |

## Quick Start

### Prerequisites

- Python 3.11+
- Node.js 18+
- {db.capitalize()} running locally (or use Docker)

### Development

```bash
# Install all dependencies and start both servers
make dev
```

Or manually:

```bash
# Backend
cd backend
python -m venv .venv && source .venv/bin/activate
pip install -r requirements.txt
{"python manage.py migrate && python manage.py runserver" if backend == "django" else "uvicorn app.main:app --reload"}

# Frontend (in another terminal)
cd frontend
npm install
npm run dev
```

### Docker

```bash
docker-compose up --build
```

## Project Structure

```
{name.lower()}/
├── backend/          # {backend.capitalize()} application
│   ├── app/          # Application code
│   │   ├── models/   # Database models (SQLAlchemy / Django ORM)
│   │   ├── routers/  # API route handlers
│   │   ├── schemas/  # Pydantic schemas / serializers
│   │   └── core/     # Config, auth, database setup
│   └── tests/        # Backend tests
├── frontend/         # React application
│   ├── src/
│   │   ├── components/  # Reusable UI components
│   │   ├── pages/       # Route-level page components
│   │   ├── services/    # API client layer
│   │   ├── hooks/       # Custom React hooks
│   │   └── store/       # State management
│   └── public/
├── docker-compose.yml
├── Makefile
└── .pyforge.json   # PyReactor Forge project metadata
```

## API Documentation

When the backend is running, visit:
- Swagger UI: http://localhost:8000/docs
- ReDoc:       http://localhost:8000/redoc

## License

MIT
"""

    def _render_makefile(self):
        backend = self.config["backend"]
        run_cmd = (
            "python manage.py runserver"
            if backend == "django"
            else "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
        )
        migrate_cmd = (
            "python manage.py migrate"
            if backend == "django"
            else "alembic upgrade head"
        )
        return f"""# Makefile for {self.name}

.PHONY: dev backend frontend install migrate test lint docker-up docker-down

dev:
\t$(MAKE) -j2 backend frontend

backend:
\tcd backend && source .venv/bin/activate && {run_cmd}

frontend:
\tcd frontend && npm run dev

install:
\tcd backend && python -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt
\tcd frontend && npm install

migrate:
\tcd backend && source .venv/bin/activate && {migrate_cmd}

test:
\tcd backend && source .venv/bin/activate && pytest
\tcd frontend && npm run test

lint:
\tcd backend && source .venv/bin/activate && ruff check . && mypy .
\tcd frontend && npm run lint

docker-up:
\tdocker-compose up --build -d

docker-down:
\tdocker-compose down
"""


ROOT_GITIGNORE = """# Python
__pycache__/
*.py[cod]
*.egg-info/
.venv/
.env
dist/
build/
.mypy_cache/
.ruff_cache/
.pytest_cache/

# Node
node_modules/
dist/
.env.local
.env.*.local

# Database
*.db
*.sqlite3

# IDE
.vscode/
.idea/
*.swp

# OS
.DS_Store
Thumbs.db

# Docker
.docker/
"""
