"""Entity generator - adds model, CRUD API, and React UI to an existing app."""

from pathlib import Path
from typing import List


PYTHON_TYPE_MAP = {
    "string": ("str", "String(255)"),
    "text": ("str", "Text"),
    "integer": ("int", "Integer"),
    "float": ("float", "Float"),
    "boolean": ("bool", "Boolean"),
    "date": ("date", "Date"),
    "datetime": ("datetime", "DateTime(timezone=True)"),
}

TS_TYPE_MAP = {
    "string": "string",
    "text": "string",
    "integer": "number",
    "float": "number",
    "boolean": "boolean",
    "date": "string",
    "datetime": "string",
}


class EntityGenerator:
    def __init__(self, name: str, fields: List[dict], app_config: dict, app_dir: Path):
        self.name = name  # PascalCase, e.g. "Product"
        self.slug = name.lower()  # "product"
        self.slug_plural = self.slug + "s"  # "products"
        self.fields = fields
        self.config = app_config
        self.app_dir = app_dir
        self.backend = app_config.get("backend", "fastapi")
        self.frontend = app_config.get("frontend", "react-ts")
        self.ts = self.frontend == "react-ts"
        self.ext = "tsx" if self.ts else "jsx"
        self.ext_plain = "ts" if self.ts else "js"
        self.created_files: List[str] = []

    def generate(self):
        if self.backend == "fastapi":
            self._fastapi_model()
            self._fastapi_schema()
            self._fastapi_router()
            self._register_fastapi_router()
        elif self.backend == "django":
            self._django_model()
            self._django_serializer()
            self._django_view()
        else:
            self._flask_model()
            self._flask_routes()

        self._frontend_service()
        self._frontend_page()
        self._register_frontend_route()

    # ─────────────────────────────────────────────
    # FastAPI
    # ─────────────────────────────────────────────

    def _fastapi_model(self):
        imports = set()
        columns = []

        for f in self.fields:
            py_type, sa_type = PYTHON_TYPE_MAP[f["type"]]
            nullable = "not null" if f["required"] else "nullable=True"

            if f["type"] in ("date", "datetime"):
                imports.add(f"from datetime import {py_type}")

            optional = "" if f["required"] else " | None = None"
            col = (
                f'    {f["name"]}: Mapped[{py_type}{optional}] = '
                f'mapped_column({sa_type}, nullable={str(not f["required"])})'
            )
            columns.append(col)

        imports_str = "\n".join(sorted(imports))
        col_str = "\n".join(columns)

        model_path = self.app_dir / "backend" / "app" / "models" / f"{self.slug}.py"
        model_path.write_text(f'''"""{ self.name } database model - generated by PyReactor Forge."""

{imports_str}
from sqlalchemy import String, Integer, Float, Boolean, Text, Date, DateTime
from sqlalchemy.orm import Mapped, mapped_column
from app.core.database import Base


class {self.name}(Base):
    __tablename__ = "{self.slug_plural}"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
{col_str}

    def __repr__(self) -> str:
        return f"<{self.name} id={{self.id}}>"
''', encoding="utf-8")
        self.created_files.append(str(model_path.relative_to(self.app_dir)))

    def _fastapi_schema(self):
        fields_base = []
        fields_create = []
        for f in self.fields:
            py_type, _ = PYTHON_TYPE_MAP[f["type"]]
            optional = "" if f["required"] else f" | None = None"
            fields_base.append(f"    {f['name']}: {py_type}{optional}")
            if f["required"]:
                fields_create.append(f"    {f['name']}: {py_type}")

        base_str = "\n".join(fields_base) or "    pass"

        schema_path = self.app_dir / "backend" / "app" / "schemas" / f"{self.slug}.py"
        schema_path.write_text(
            f'''"""{self.name} Pydantic schemas - generated by PyReactor Forge."""

from pydantic import BaseModel


class {self.name}Base(BaseModel):
{base_str}


class {self.name}Create({self.name}Base):
    pass


class {self.name}Update(BaseModel):
{chr(10).join(f"    {f['name']}: {PYTHON_TYPE_MAP[f['type']][0]} | None = None" for f in self.fields) or "    pass"}


class {self.name}Read({self.name}Base):
    id: int
    model_config = {{"from_attributes": True}}
''', encoding="utf-8")
        self.created_files.append(str(schema_path.relative_to(self.app_dir)))

    def _fastapi_router(self):
        router_path = self.app_dir / "backend" / "app" / "routers" / f"{self.slug_plural}.py"
        router_path.write_text(f'''"""{self.name} CRUD router - generated by PyReactor Forge."""

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func

from app.core.database import get_db
from app.core.deps import get_current_user
from app.models.{self.slug} import {self.name}
from app.schemas.{self.slug} import {self.name}Create, {self.name}Update, {self.name}Read

router = APIRouter()


@router.get("/", response_model=list[{self.name}Read])
async def list_{self.slug_plural}(
    page: int = Query(1, ge=1),
    size: int = Query(20, ge=1, le=100),
    db: AsyncSession = Depends(get_db),
    _=Depends(get_current_user),
):
    offset = (page - 1) * size
    result = await db.execute(select({self.name}).offset(offset).limit(size))
    return result.scalars().all()


@router.post("/", response_model={self.name}Read, status_code=201)
async def create_{self.slug}(
    data: {self.name}Create,
    db: AsyncSession = Depends(get_db),
    _=Depends(get_current_user),
):
    obj = {self.name}(**data.model_dump())
    db.add(obj)
    await db.commit()
    await db.refresh(obj)
    return obj


@router.get("/{{id}}", response_model={self.name}Read)
async def get_{self.slug}(
    id: int,
    db: AsyncSession = Depends(get_db),
    _=Depends(get_current_user),
):
    result = await db.execute(select({self.name}).where({self.name}.id == id))
    obj = result.scalar_one_or_none()
    if not obj:
        raise HTTPException(status_code=404, detail="{self.name} not found")
    return obj


@router.patch("/{{id}}", response_model={self.name}Read)
async def update_{self.slug}(
    id: int,
    data: {self.name}Update,
    db: AsyncSession = Depends(get_db),
    _=Depends(get_current_user),
):
    result = await db.execute(select({self.name}).where({self.name}.id == id))
    obj = result.scalar_one_or_none()
    if not obj:
        raise HTTPException(status_code=404, detail="{self.name} not found")
    for key, val in data.model_dump(exclude_unset=True).items():
        setattr(obj, key, val)
    await db.commit()
    await db.refresh(obj)
    return obj


@router.delete("/{{id}}", status_code=204)
async def delete_{self.slug}(
    id: int,
    db: AsyncSession = Depends(get_db),
    _=Depends(get_current_user),
):
    result = await db.execute(select({self.name}).where({self.name}.id == id))
    obj = result.scalar_one_or_none()
    if not obj:
        raise HTTPException(status_code=404, detail="{self.name} not found")
    await db.delete(obj)
    await db.commit()
''', encoding="utf-8")
        self.created_files.append(str(router_path.relative_to(self.app_dir)))

    def _register_fastapi_router(self):
        main_path = self.app_dir / "backend" / "app" / "main.py"
        if not main_path.exists():
            return
        content = main_path.read_text(encoding="utf-8")
        import_line = f"from app.routers import {self.slug_plural}"
        register_line = (
            f'app.include_router({self.slug_plural}.router, '
            f'prefix="/api/{self.slug_plural}", tags=["{self.slug_plural}"])'
        )
        if import_line not in content:
            # Insert after last import block
            lines = content.split("\n")
            insert_at = 0
            for i, line in enumerate(lines):
                if line.startswith("from app.routers import"):
                    insert_at = i + 1
            lines.insert(insert_at, import_line)
            content = "\n".join(lines)

        if register_line not in content:
            content += f"\n{register_line}\n"

        main_path.write_text(content, encoding="utf-8")
        self.created_files.append("backend/app/main.py (updated)")

    # ─────────────────────────────────────────────
    # Django
    # ─────────────────────────────────────────────

    def _django_model(self):
        fields_str = "\n".join(
            f"    {f['name']} = models.{'Char' if f['type'] == 'string' else f['type'].capitalize()}Field("
            f"{'max_length=255, ' if f['type'] == 'string' else ''}null={str(not f['required'])}, blank={str(not f['required'])})"
            for f in self.fields
        )
        out = self.app_dir / "backend" / "api" / f"models_{self.slug}.py"
        out.write_text(f'''from django.db import models


class {self.name}(models.Model):
{fields_str}
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.name} #{{self.pk}}"
''', encoding="utf-8")
        self.created_files.append(str(out.relative_to(self.app_dir)))

    def _django_serializer(self):
        out = self.app_dir / "backend" / "api" / f"serializers_{self.slug}.py"
        out.write_text(f'''from rest_framework import serializers
from .models_{self.slug} import {self.name}


class {self.name}Serializer(serializers.ModelSerializer):
    class Meta:
        model = {self.name}
        fields = "__all__"
''', encoding="utf-8")
        self.created_files.append(str(out.relative_to(self.app_dir)))

    def _django_view(self):
        out = self.app_dir / "backend" / "api" / f"views_{self.slug}.py"
        out.write_text(f'''from rest_framework.viewsets import ModelViewSet
from .models_{self.slug} import {self.name}
from .serializers_{self.slug} import {self.name}Serializer


class {self.name}ViewSet(ModelViewSet):
    queryset = {self.name}.objects.all()
    serializer_class = {self.name}Serializer
''', encoding="utf-8")
        self.created_files.append(str(out.relative_to(self.app_dir)))

    # ─────────────────────────────────────────────
    # Flask
    # ─────────────────────────────────────────────

    def _flask_model(self):
        cols = "\n".join(
            f"    {f['name']} = db.Column(db.{'String(255)' if f['type'] == 'string' else f['type'].capitalize()}, nullable={str(not f['required'])})"
            for f in self.fields
        )
        out = self.app_dir / "backend" / "app" / f"model_{self.slug}.py"
        out.write_text(f'''from . import db


class {self.name}(db.Model):
    __tablename__ = "{self.slug_plural}"
    id = db.Column(db.Integer, primary_key=True)
{cols}
''', encoding="utf-8")
        self.created_files.append(str(out.relative_to(self.app_dir)))

    def _flask_routes(self):
        out = self.app_dir / "backend" / "app" / f"routes_{self.slug}.py"
        out.write_text(f'''from flask import Blueprint, request, jsonify
from flask_jwt_extended import jwt_required
from . import db
from .model_{self.slug} import {self.name}

{self.slug_plural}_bp = Blueprint("{self.slug_plural}", __name__)


@{self.slug_plural}_bp.get("/")
@jwt_required()
def list_{self.slug_plural}():
    items = {self.name}.query.all()
    return jsonify([{{"id": i.id, {", ".join(f'"{f["name"]}": getattr(i, "{f["name"]}")' for f in self.fields)}}} for i in items])


@{self.slug_plural}_bp.post("/")
@jwt_required()
def create_{self.slug}():
    data = request.get_json()
    obj = {self.name}(**data)
    db.session.add(obj)
    db.session.commit()
    return jsonify({{"id": obj.id}}), 201
''', encoding="utf-8")
        self.created_files.append(str(out.relative_to(self.app_dir)))

    # ─────────────────────────────────────────────
    # Frontend
    # ─────────────────────────────────────────────

    def _frontend_service(self):
        ts_interface = ""
        if self.ts:
            fields_ts = "\n".join(
                f"  {f['name']}: {TS_TYPE_MAP[f['type']]}{'  // optional' if not f['required'] else ''};"
                for f in self.fields
            )
            ts_interface = f"""export interface {self.name} {{
  id: number;
{fields_ts}
}}

"""

        svc_path = self.app_dir / "frontend" / "src" / "services" / f"{self.slug}Service.{self.ext_plain}"
        svc_path.write_text(f'''{ts_interface}import api from "./api";

export const {self.slug}Service = {{
  list: async (page = 1, size = 20) => {{
    const res = await api.get("/{self.slug_plural}/", {{ params: {{ page, size }} }});
    return res.data{f" as {self.name}[]" if self.ts else ""};
  }},

  get: async (id: number) => {{
    const res = await api.get(`/{self.slug_plural}/${{id}}`);
    return res.data{f" as {self.name}" if self.ts else ""};
  }},

  create: async (data: {"Omit<" + self.name + ", 'id'>" if self.ts else "object"}) => {{
    const res = await api.post("/{self.slug_plural}/", data);
    return res.data{f" as {self.name}" if self.ts else ""};
  }},

  update: async (id: number, data: {"Partial<" + self.name + ">" if self.ts else "object"}) => {{
    const res = await api.patch(`/{self.slug_plural}/${{id}}`, data);
    return res.data{f" as {self.name}" if self.ts else ""};
  }},

  delete: async (id: number) => {{
    await api.delete(`/{self.slug_plural}/${{id}}`);
  }},
}};
''', encoding="utf-8")
        self.created_files.append(str(svc_path.relative_to(self.app_dir)))

    def _frontend_page(self):
        columns_jsx = "\n".join(
            f'          <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">{f["name"]}</th>'
            for f in self.fields
        )
        cells_jsx = "\n".join(
            f'          <td className="px-4 py-3 text-sm text-gray-700">{{String(item.{f["name"]} ?? "-")}}</td>'
            for f in self.fields
        )

        page_path = self.app_dir / "frontend" / "src" / "pages" / f"{self.name}Page.{self.ext}"
        page_path.write_text(f'''import {{ useQuery }} from "@tanstack/react-query";
import {{ {self.slug}Service }} from "../services/{self.slug}Service";

export default function {self.name}Page() {{
  const {{ data: items = [], isLoading, error }} = useQuery({{
    queryKey: ["{self.slug_plural}"],
    queryFn: () => {self.slug}Service.list(),
  }});

  if (isLoading) {{
    return <div className="flex items-center justify-center h-64 text-gray-400">Loading {self.slug_plural}...</div>;
  }}

  if (error) {{
    return <div className="p-8 text-red-500">Failed to load {self.slug_plural}.</div>;
  }}

  return (
    <div className="p-8">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold text-gray-900">{self.name}s</h1>
        <button className="bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors">
          + Add {self.name}
        </button>
      </div>

      <div className="bg-white border rounded-xl overflow-hidden">
        <table className="w-full">
          <thead className="bg-gray-50 border-b">
            <tr>
              <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">ID</th>
{columns_jsx}
              <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {{items.map((item) => (
              <tr key={{item.id}} className="hover:bg-gray-50 transition-colors">
                <td className="px-4 py-3 text-sm text-gray-500">{{item.id}}</td>
{cells_jsx}
                <td className="px-4 py-3 text-right">
                  <button className="text-xs text-blue-600 hover:underline mr-3">Edit</button>
                  <button className="text-xs text-red-500 hover:underline">Delete</button>
                </td>
              </tr>
            ))}}
            {{items.length === 0 && (
              <tr>
                <td colSpan={{99}} className="px-4 py-8 text-center text-gray-400 text-sm">
                  No {self.slug_plural} yet.
                </td>
              </tr>
            )}}
          </tbody>
        </table>
      </div>
    </div>
  );
}}
''', encoding="utf-8")
        self.created_files.append(str(page_path.relative_to(self.app_dir)))

    def _register_frontend_route(self):
        app_path = self.app_dir / "frontend" / "src" / f"App.{self.ext}"
        if not app_path.exists():
            return
        content = app_path.read_text(encoding="utf-8")
        import_line = f'import {self.name}Page from "./pages/{self.name}Page";'
        route_line = f'          <Route path="/{self.slug_plural}" element={{<{self.name}Page />}} />'

        if import_line not in content:
            content = import_line + "\n" + content
        if route_line not in content:
            content = content.replace(
                '          <Route index element={<DashboardPage />} />',
                f'          <Route index element={{<DashboardPage />}} />\n{route_line}'
            )
        app_path.write_text(content, encoding="utf-8")
        self.created_files.append("frontend/src/App.tsx (updated)")
